### ISSUE TITLE
last commit broke package

### ISSUE THREAD

**Issue by damian0604** [amcat/amcatclient#5] opened 2015-04-18 23:05 UTC
Hi all,

After trying to get the client running for hours, I figured out that the last commit (https://github.com/amcat/amcatclient/commit/77e508dfe011b68ef1f57ebd5993ef2a4d26778e ) seems to have broken the client, at least for me. 
After reverting to https://raw.githubusercontent.com/amcat/amcatclient/741557f9a0a92276fc7bdca1d03f280973a4ac57/amcatclient/amcatclient.py , I could use the client without problems. In particular, my attempts to use the list_articles function returned a 500 Error:
Full error retrieved by the request:
{'error': True, 'status': 500, 'description': 'The server encountered an internal error or misconfiguration and\n                     was unable to complete your request.', 'details': "KeyError: 'get'", 'message': '500 : An Error has occurred'}
Best,
Damian

**Comment by vanatteveldt** [comment] 2015-04-19 08:05
Thanks for reporting! I'll have a look.

**Comment by damian0604** [comment] 2015-04-19 09:30
Super, dankjewel Wouter! Sowieso geweldig dat jullie dit beschikbaar stellen!

**Comment by vanatteveldt** [comment] 2015-04-19 10:45
I'm sorry the "confirmed" above is a stupid mistake, I mistyped the set id (see 18196 vs 18916). Testing with an actual set number works fine. 

I'm closing the issue, can you double check your set id, and if you still have problems, post the python code that generates the error?

**Comment by damian0604** [comment] 2015-04-19 11:35
Triple- and quadruple-checked the set numbers. Works with the old commit, but not with the new one. Did it on MacOS as well as an Ubuntu-VM. I can also access the data via a browser.
(and yes, the XXXX weren't there before I pasted it here ;-) )

```
air-van-damian:amcattest damian$ cat ex.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from amcatclient import AmcatAPI
api = AmcatAPI('https://amcat.nl', 'XXXXXXX','XXXXXXX')
articles = api.list_articles(project='769', articleset='15455')
articles = [art for art in articles]
print(articles[0].keys())
print(articles[0])
air-van-damian:amcattest damian$ ./ex.py 
Traceback (most recent call last):
  File "./ex.py", line 9, in <module>
    articles = [art for art in articles]
  File "./ex.py", line 9, in <listcomp>
    articles = [art for art in articles]
  File "/Users/damian/Desktop/amcattest/amcatclient.py", line 194, in get_pages
    r = self.request(url, page=page, page_size=page_size, **filters)
  File "/Users/damian/Desktop/amcattest/amcatclient.py", line 190, in request
    return check(r, expected_status=expected_status)
  File "/Users/damian/Desktop/amcattest/amcatclient.py", line 99, in check
    err, err["description"], err["details"])
amcatclient.APIError: [Errno 500] 500 : An Error has occurred: 'https://amcat.nl/api/v4/projects/769/articlesets/15455/articles/'
air-van-damian:amcattest damian$ 
```

**Comment by vanatteveldt** [comment] 2015-04-19 11:39
Running the code now, it takes a while before it errors.

BTW, you can store your username/pwd in ~/.amcatauth to prevent it appearing in scripts.

**Comment by vanatteveldt** [comment] 2015-04-19 11:43
The code works "on my computer"

```{python}
$ PYTHONPATH=. python ~/ex.py
No handlers could be found for logger "amcatclient"
[u'metastring', u'byline', u'uuid', u'parent', u'author', u'headline', u'text', u'section', u'insertscript', u'project', u'url', u'length', u'addressee', u'externalid', u'insertdate', u'date', u'medium', u'pagenr', u'id', u'mediumid']
{u'metastring': None, u'byline': u'', u'uuid': u'88ac453b-003a-43d3-94e7-4a172f38f317', u'parent': None, u'author': None, u'headline': u'Barack Obama', u'text': u'It is our unfinished task to restore the basic bargain that built this country: the idea that if you work hard and meet your responsibilities, you can get ahead, no matter where you come from, no matter what you look like or who you love. ', u'section': None, u'insertscript': None, u'project': 559, u'url': None, u'length': 62, u'addressee': None, u'externalid': None, u'insertdate': u'2014-09-24T17:56:29.632', u'date': u'2013-02-12T00:00:00', u'medium': u'Democrats', u'pagenr': 5, u'id': 111541965, u'mediumid': 989900291}
$ cat ~/ex.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from amcatclient import AmcatAPI
api = AmcatAPI('https://amcat.nl')
articles = api.list_articles(project='769', articleset='15455')
articles = [art for art in articles]
print(articles[0].keys())
print(articles[0])
```

I'll check whether it also works if I try from a non-admin account

**Comment by vanatteveldt** [comment] 2015-04-19 11:50
I still can't reproduce...

```{python}
$ cat ~/ex.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from amcatclient import AmcatAPI
api = AmcatAPI('https://amcat.nl', 'test', 'XXX')
#api = AmcatAPI('https://amcat.nl')
articles = api.list_articles(project='769', articleset='15455')
articles = [art for art in articles]
print(articles[0].keys())
print(articles[0])
$ PYTHONPATH=. python ~/ex.py
No handlers could be found for logger "amcatclient"
[u'metastring', u'byline', u'uuid', u'parent', u'author', u'headline', u'text', u'section', u'insertscript', u'project', u'url', u'length', u'addressee', u'externalid', u'insertdate', u'date', u'medium', u'pagenr', u'id', u'mediumid']
{u'metastring': None, u'byline': u'', u'uuid': u'88ac453b-003a-43d3-94e7-4a172f38f317', u'parent': None, u'author': None, u'headline': u'Barack Obama', u'text': u'It is our unfinished task to restore the basic bargain that built this country: the idea that if you work hard and meet your responsibilities, you can get ahead, no matter where you come from, no matter what you look like or who you love. ', u'section': None, u'insertscript': None, u'project': 559, u'url': None, u'length': 62, u'addressee': None, u'externalid': None, u'insertdate': u'2014-09-24T17:56:29.632', u'date': u'2013-02-12T00:00:00', u'medium': u'Democrats', u'pagenr': 5, u'id': 111541965, u'mediumid': 989900291}
```

I've pushed the more detailed error message, could you update (git pull) your amcatclient, try again, and post the error message?

**Comment by damian0604** [comment] 2015-04-19 12:08
Hi Wouter, I did that before (printing the whole error message, see first post), showing that the error was something like "KeyError: 'get'" and not, e.g., related to wrong credentials (which I tried as well and which produces a different error message). I know pulled amcatclient again, and it basically gives the same (key error: 'get')

```
Traceback (most recent call last):
  File "./ex.py", line 9, in <module>
    articles = [art for art in articles]
  File "./ex.py", line 9, in <listcomp>
    articles = [art for art in articles]
  File "/Users/damian/Desktop/amcattest/amcatclient.py", line 197, in get_pages
    r = self.request(url, page=page, page_size=page_size, **filters)
  File "/Users/damian/Desktop/amcattest/amcatclient.py", line 193, in request
    return check(r, expected_status=expected_status)
  File "/Users/damian/Desktop/amcattest/amcatclient.py", line 102, in check
    err, err["description"], err["details"])
amcatclient.APIError: [Errno 500] 500 : An Error has occurred: 'https://amcat.nl/api/v4/projects/769/articlesets/15455/articles/': The server encountered an internal error or misconfiguration and
                     was unable to complete your request.; KeyError: 'get'
```

**Comment by vanatteveldt** [comment] 2015-04-19 12:32
Hey Damian, yeah I saw the earlier error, but I updated the code to give more details, so now we know that it is a 'keyerror: get'. Grepping that in the server logs reveals  that it does seem to be a problem related to permissions:

```
  File "./api/rest/viewsets/project.py", line 71, in has_permission
    required_role_id = _DEFAULT_PERMISSION_MAP[request.method]
KeyError: 'get'^[[39;49;0m
```

I think that this is indeed connected to the 'method override' fix, but it's strange that I'm not getting the error myself...

**Comment by vanatteveldt** [comment] 2015-04-19 12:36
I've pushed a fix, can you verify that it works?

https://github.com/amcat/amcat/commit/16725ae7a9c2670c20a58a25693271e212844f95

**Closed by vanatteveldt** 2015-04-19 12:36 UTC
Labels: bug

**Comment by damian0604** [comment] 2015-04-19 12:47
Works! Thanks!!!

**Comment by vanatteveldt** [comment] 2015-04-19 13:21
Excellent, thanks for helping us debug this one!
